Number	Votes	Question
Q1	1	why does my `main()` doesn&#39;t catch exception thrown in a `timer` in a junit test?